version: '3.3'
services:
  web-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: ${CI_REGISTRY_PREFIX}/web-app
    container_name: web-app
    env_file: env/.prod.env
    restart: always
    labels:
      - traefik.http.routers.web-app-secure.rule=Host(`kicksware.com`)
      - traefik.http.routers.web-app-secure.tls=true
      - traefik.http.routers.web-app-secure.tls.certresolver=le
      - traefik.http.routers.web-app.rule=Host(`kicksware.com`)
      - traefik.http.routers.web-app.middlewares=https-redirect
      - traefik.docker.network=web
    networks:
      - web
    volumes:
      - type: bind
        source: /source/storage
        target: /app/wwwroot/storage
      - type: bind
        source: /source/keys
        target: /keys
      - type: bind
        source: /${SOURCE_DIR}/web-app/Web/node_modules
        target: /app/node_modules
networks:
  web:
    external: true
