project: kicksware
component: web-app
nameOverride: web-app
fullnameOverride: web-app
replicaCount: 2

image:
  registry: timothydockid
  repository: kicksware-web-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure
  tls:
    enabled: true
    certResolver: le
    secretName: temp-tls
  routes:
    - host: kicksware.com
      paths:
        - /
      middlewares: []
      services:
        - name: web-app
          port: 80
          scheme: http
    - host: www.kicksware.com
      paths:
        - /
      middlewares: []
      services:
        - name: web-app
          port: 80
          scheme: http
    - host: health.kicksware.com
      paths:
        - /
      middlewares:
        - name: health-add
      services:
        - name: web-app
          port: 80
          scheme: http

volumes:
  - name: storage
    persistent:
      claim: content
      exists: true
    mountPath: /source/storage
  - name: keys
    persistent:
      claim: webapp-keys
      storageClass: longhorn
      size: 250Mi
      accessModes:
        - ReadWriteMany
    mountPath: /keys

resources:
  requests:
    cpu: 100m
    memory: 250Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilization: 500

serviceAccount:
  create: true
  annotations: {}
  name: ""

secrets:
  mounts:
    - name: grpc-tls
      mountPath: /app/certs
  environment:
    - google-oauth
    - facebook-oauth
    - github-oauth
    - api-access

config:
  environment: PROD

environment:
  name: PROD
  aspEnviroment: Production
  aspnetURL: http://0.0.0.0:80
  apiURL: https://rpc.kicksware.com
  storagePath: https://cdn.kicksware.com
  localStroragePath: /source/storage
  tlsCertFile: /app/certs/tls.crt
  dataProtocol: grpc
