project: kicksware
component: web-app
nameOverride: web-app
fullnameOverride: web-app
replicaCount: 1

image:
  registry: registry.kicksware.com
  repository: web-app
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure
  tls:
    enabled: true
    certResolver: le
  routes:
    - host: kicksware.com
      paths:
        - /
      middlewares: []
      services:
        - name: web-app
          port: 80
          scheme: http
    - host: www.kicksware.com
      paths:
        - /
      middlewares: []
      services:
        - name: web-app
          port: 80
          scheme: http

volumes:
  - name: storage
    persistent:
      claim: webapp-storage
      storageClass: nfs
      size: 25Gi
      accessModes:
        - ReadWriteMany
    mountPath: /source/storage
  - name: keys
    persistent:
      claim: webapp-keys
      storageClass: nfs
      size: 250Mi
      accessModes:
        - ReadWriteOnce
    mountPath: /keys

resources: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: true
  annotations: {}
  name: ""

secrets:
  dockerRegistry: registry-token
  mounts:
    - name: grpc-tls
      mountPath: /app/certs
  environment:
    - google-oauth
    - facebook-oauth

config:
  environment: PROD