{{- with .Values.environment }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chart.fullname" . }}.env
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  ENV: {{ .name }}
  ASPNETCORE_ENVIRONMENT: {{ .aspEnviroment }}
  ASPNETCORE_URLS: {{ .aspnetURL }}
  GATEWAY_API_URL: {{ .apiURL }}
  STORAGE_PATH: {{ .storagePath }}
  LOCAL_STORAGE_PATH: {{ .localStroragePath }}
  TLS_CERT_FILE: {{ .tlsCertFile }}
{{- end }}